[package]
name = "rust-google-translate"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]

[dependencies]
hyper = "*"
gdk = "0.3.0"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_10"]
